In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [17]:
b=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(b)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [18]:
# getting shape
b.shape

(2, 5)

In [11]:
# Getting type
a.dtype    # dtype is data type

dtype('int32')

In [19]:
# Getting Dimension
b.ndim

2

In [21]:
# Getting size
a.itemsize

4

In [24]:
# Getting total size
b.nbytes   # size in bytes

40

In [30]:
# Getting specific element [r,c]
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,2]                 # getting data from matrix 



10

In [31]:
# Getting specific row
a[1,:]       # (1,:) all data from 1st row

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
# Getting specific column
a[:,2]       # (:,1) all data from 1st column

array([ 3, 10])

In [36]:
# getting more fancy (start inde: end index: step size)
a[1,1:5:2]      

array([ 9, 11])

In [45]:
# Changing value from array
a[0,4]=999
print(a)

[[  1   2   3   4 999   6   7]
 [  8 100 100 100 100  13  14]]


In [47]:
# 3-D Array
x=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [50]:
# getting specific element
x[:,1,:]                

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [56]:
# Replace
x[:,1,:]= [[111,222,333,444],[555,666,777,888]]
print(x)

[[[111 222 333 444]
  [111 222 333 444]]

 [[555 666 777 888]
  [555 666 777 888]]]


In [85]:
# all ones matrix
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [159]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
# all zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
# any other no. in matrix form
np.full((2,3),111)

array([[111, 111, 111],
       [111, 111, 111]])

In [81]:
# random decimal no.
np.random.rand(2,3)

array([[0.61083949, 0.93019277, 0.8956923 ],
       [0.20702871, 0.2101077 , 0.49691317]])

In [86]:
np.random.random_sample(x.shape)               # getting matrix size of x as a sample

array([[[0.2870592 , 0.3967275 , 0.09580018, 0.83634489],
        [0.03861732, 0.09895286, 0.56605801, 0.54011062]],

       [[0.29412969, 0.7989034 , 0.46848056, 0.85999161],
        [0.40021811, 0.41053003, 0.99144058, 0.63245839]]])

In [89]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
# Repeat an array
a=np.array([[1,2,3]])
r=np.repeat(a,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [106]:
a=np.array([1,2,3])
r=np.repeat(a,4,axis=0)
print(r)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [111]:
a=np.array([[1,2,3]])
r=np.repeat(a,3,axis=1)
print(r)

[[1 1 1 2 2 2 3 3 3]]


In [108]:
a=np.array([[1,2,3]])
r=np.repeat(a,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [117]:
################ ********* ###############
a=np.ones((5,5))
b=np.zeros((3,3))
b[1,1]=9
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [119]:
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [121]:
# Mathematics
a=np.array([2,3,4,5,6])
a+=2
print(a)

[4 5 6 7 8]


In [123]:
a=np.array([2,3,4,5,6])
a-=2
print(a)

[0 1 2 3 4]


In [125]:
a=np.array([2,3,4,5,6])
a*=2
print(a)

[ 4  6  8 10 12]


In [129]:
a=np.array([2,3,4,5,6])
a=a/2
print(a)

[1.  1.5 2.  2.5 3. ]


In [130]:
a=np.array([2,3,4,5,6])
a**=2
print(a)

[ 4  9 16 25 36]


In [131]:
a=np.array([2,3,4,5,6])
a=np.sin(a)
print(a)

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [132]:
a=np.array([2,3,4,5,6])
np.cos(a)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [134]:
# Linear Algebra
a=np.ones((2,3))
b=np.full((3,2),3)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [137]:
# for multipication of two matrix
np.matmul(a,b)          # matmul is matri multiplication

array([[9., 9.],
       [9., 9.]])

In [140]:
# Finding Determinant
c=np.identity(4)
np.linalg.det(c)       # for finding the determinant

1.0

In [142]:
# Statistics
stats=np.array([[1,2,3,4],[5,6,7,8]])
print(stats)

[[1 2 3 4]
 [5 6 7 8]]


In [143]:
np.min(stats)

1

In [145]:
np.min(stats,axis=0)   # axis=0 for row

array([1, 2, 3, 4])

In [146]:
np.min(stats,axis=1)    # axis=1 for column

array([1, 5])

In [147]:
np.max(stats)

8

In [148]:
np.max(stats,axis=0)

array([5, 6, 7, 8])

In [149]:
np.max(stats,axis=1)

array([4, 8])

In [150]:
np.sum(stats)

36

In [151]:
np.sum(stats,axis=1)

array([10, 26])

In [152]:
np.sum(stats,axis=0)

array([ 6,  8, 10, 12])

In [153]:
# Vertical stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])              # stack or vstack are same and used for vertical stacking
V=np.vstack([v1,v2])
print(V)

[[1 2 3 4]
 [5 6 7 8]]


In [154]:
V=np.vstack([v1,v2,v2])
print(V)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [157]:
V=np.vstack([v1,v1,v1,v2,v2])
print(V)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [158]:
# Horizontal stacking vectors
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])
H=np.hstack([h1,h2])
print(H)

[1 2 3 4 5 6 7 8]


In [59]:
import numpy as np
a=np.array([[1,2],[4,5]])
b=np.array([[11,12],[23,45]])
x=np.linalg.inv(a).dot(b)
x

array([[-3., 10.],
       [ 7.,  1.]])

In [60]:
a.T

array([[1, 4],
       [2, 5]])

In [90]:
np.random.randint(9, size=(4, 4))

array([[0, 2, 0, 7],
       [2, 3, 5, 5],
       [1, 3, 5, 6],
       [2, 0, 7, 4]])

In [97]:
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)
a=pd.read_excel("C:\\Users\\ANKIT\\Desktop\\Excel_DATA.xlsx",sheet_name="Data",skiprows=1)
a

rollno. firstname lastname  salary  Age
0        8     ankit    kumar   63711   12
1        3      amit   chadda   44738   13
2        2      juli    verma   22269   12
3        7     mummy    kumar   64149   15
4       10      papa    kumar   57826   14
5        6    ankush    kumar   79000   13
6        4      amit    sinha   31950   12
7        1      anki   sharma   21715   12
8        9    khavar    sinha   45658   15
9        5      goli    sinha   57246   11